version: '3'

services:
  app_db:
    image: postgres:14.2
    ports:
      - 5439:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crispy_happiness
  app_test_db:
    image: postgres:14.2
    ports:
      - 5440:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crispy_happiness_test
